### ISSUE TITLE
[Bug] Projen tasks are not run from the project root

### ISSUE THREAD

**Issue by straygar** [MarkMcCulloh/vscode-projen#14]
**Describe the bug**
When running projen tasks from the side panel, they are executed in the currently open terminal, in whatever folder you're in at that moment, resulting in a "Unknown command: x" error 

**To Reproduce**
1. In VSCode, have a terminal open in your project root
2. Navigate to a subdirectory (e.g. `cdk`)
3. In the extension sidebar, press ▶️ on any task (e.g. `install`)
4. The task fails with: `Unknown command: install`

**Expected behavior**
The task is run successfully.

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur

**Comment by MarkMcCulloh** [comment]
The latest version (0.0.13) has a fix for this! 
Feel free to reopen if it doesn't work for you, I was not able to test it on mac but I think it should work.
