### ISSUE TITLE
[Bug] Some files are not marked as projen-generated

### ISSUE THREAD

**Issue by Chriscbr** [MarkMcCulloh/vscode-projen#15]
**Describe the bug**
YAML files generated by projen aren't marked in the file tree as generated by projen. These files start with `# ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".` so I think they should be tagged.

**To Reproduce**
Try loading https://github.com/projen/projen with the extension, and inspect the `.github/workflows/` folder.

**Expected behavior**
`auto-approve.yml` and other files on should be tagged with "PJ".

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS 11.6.1

**Additional context**
N/A

**Comment by Chriscbr** [comment]
I also wonder if it's possible to automatically mark directories as projen-generated (so they appear de-emphasized / marked with "PJ" whenever all of their files and subdirectories are also projen-generated).

**Comment by MarkMcCulloh** [comment]
I mentioned this in the [readme](https://github.com/MarkMcCulloh/vscode-projen#current-limitations) but I should have made an issue for it, so thanks for putting one in.

Basically, right now this plugin doesn't scan everything to look for projen-managed files. This was deliberate, as without knowing what to exclude, it would be possible to waste a lot of system resources scanning irrelevant files. I'll retitle this to cover this issue.

My current plan was to lean on the eventual implementation of https://github.com/projen/projen/issues/1265 to get the full list of files.

**Comment by MarkMcCulloh** [comment]
Using the change from https://github.com/projen/projen/issues/1265, this change is now available in v0.0.15! The latest version of projen would be needed to see the change.
Also included is doing the same for directories that are completely managed by projen.
